# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "D:\Program Files\CodeBlocks\MinGW\bin\cmake.exe"

# The command to remove a file.
RM = "D:\Program Files\CodeBlocks\MinGW\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\Documents\Studies\Bachelor\UIT\HKI\KyNangNgheNghiep\SS004.10\tetris-game

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\Documents\Studies\Bachelor\UIT\HKI\KyNangNgheNghiep\SS004.10\tetris-game

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	"D:\Program Files\CodeBlocks\MinGW\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"D:\Program Files\CodeBlocks\MinGW\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Documents\Studies\Bachelor\UIT\HKI\KyNangNgheNghiep\SS004.10\tetris-game\CMakeFiles D:\Documents\Studies\Bachelor\UIT\HKI\KyNangNgheNghiep\SS004.10\tetris-game\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Documents\Studies\Bachelor\UIT\HKI\KyNangNgheNghiep\SS004.10\tetris-game\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tetris-game

# Build rule for target.
tetris-game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 tetris-game
.PHONY : tetris-game

# fast build rule for target.
tetris-game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tetris-game.dir\build.make CMakeFiles/tetris-game.dir/build
.PHONY : tetris-game/fast

src/colors.obj: src/colors.cpp.obj
.PHONY : src/colors.obj

# target to build an object file
src/colors.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tetris-game.dir\build.make CMakeFiles/tetris-game.dir/src/colors.cpp.obj
.PHONY : src/colors.cpp.obj

src/colors.i: src/colors.cpp.i
.PHONY : src/colors.i

# target to preprocess a source file
src/colors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tetris-game.dir\build.make CMakeFiles/tetris-game.dir/src/colors.cpp.i
.PHONY : src/colors.cpp.i

src/colors.s: src/colors.cpp.s
.PHONY : src/colors.s

# target to generate assembly for a file
src/colors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tetris-game.dir\build.make CMakeFiles/tetris-game.dir/src/colors.cpp.s
.PHONY : src/colors.cpp.s

src/game.obj: src/game.cpp.obj
.PHONY : src/game.obj

# target to build an object file
src/game.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tetris-game.dir\build.make CMakeFiles/tetris-game.dir/src/game.cpp.obj
.PHONY : src/game.cpp.obj

src/game.i: src/game.cpp.i
.PHONY : src/game.i

# target to preprocess a source file
src/game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tetris-game.dir\build.make CMakeFiles/tetris-game.dir/src/game.cpp.i
.PHONY : src/game.cpp.i

src/game.s: src/game.cpp.s
.PHONY : src/game.s

# target to generate assembly for a file
src/game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tetris-game.dir\build.make CMakeFiles/tetris-game.dir/src/game.cpp.s
.PHONY : src/game.cpp.s

src/grid.obj: src/grid.cpp.obj
.PHONY : src/grid.obj

# target to build an object file
src/grid.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tetris-game.dir\build.make CMakeFiles/tetris-game.dir/src/grid.cpp.obj
.PHONY : src/grid.cpp.obj

src/grid.i: src/grid.cpp.i
.PHONY : src/grid.i

# target to preprocess a source file
src/grid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tetris-game.dir\build.make CMakeFiles/tetris-game.dir/src/grid.cpp.i
.PHONY : src/grid.cpp.i

src/grid.s: src/grid.cpp.s
.PHONY : src/grid.s

# target to generate assembly for a file
src/grid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tetris-game.dir\build.make CMakeFiles/tetris-game.dir/src/grid.cpp.s
.PHONY : src/grid.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tetris-game.dir\build.make CMakeFiles/tetris-game.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tetris-game.dir\build.make CMakeFiles/tetris-game.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tetris-game.dir\build.make CMakeFiles/tetris-game.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... tetris-game
	@echo ... src/colors.obj
	@echo ... src/colors.i
	@echo ... src/colors.s
	@echo ... src/game.obj
	@echo ... src/game.i
	@echo ... src/game.s
	@echo ... src/grid.obj
	@echo ... src/grid.i
	@echo ... src/grid.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

